### PR TITLE
chore: remove unused dependency

### PR DESCRIPTION
**Pull request by ammgws**
Only mention of colorama is the initial commit, and nothing in the current code. Builds fine without colorama.

```
>git log -S colorama
commit 72643be454f4b591d62727dd49b217e93fccaa92
Author: Werner Robitza <werner.robitza@gmail.com>
Date:   Mon Mar 1 13:37:41 2021 +0100

    initial commit
```

### CODE REVIEW

**Comment by slhck** [comment]
That makes sense, no idea where this came from. Thanks!

**Comment by slhck** [comment]
Released as v0.7.9.

**Comment by slhck** [comment]
Actually I now understand why this was included, see https://github.com/slhck/ffmpeg-normalize/issues/131 — this is a completely optional dependency that only affects nested progress bars under Windows. As it's still a dependency of `ffmpeg-normalize`, I will leave it in there.

**Comment by micwoj92** [comment]
@slhck For your comment https://github.com/slhck/ffmpeg-normalize/issues/131#issuecomment-649013808

Setuptools has possibility for platform specific dependencies https://setuptools.pypa.io/en/latest/userguide/dependency_management.html#platform-specific-dependencies

**Comment by slhck** [comment]
Good point, @micwoj92, I pushed that to ffmpeg-normalize.

**Pull request merged**
